package liquibase.action.core;

import liquibase.action.AbstractAction;
import liquibase.structure.ObjectReference;
import liquibase.util.StringClauses;

/**
 * Alters the given table to the {@link #newDefinition}. This action is not normally directly used but is instead generated by other Actions' ActionLogic.
 */
public class AlterTableAction extends AbstractAction {

    public ObjectReference table;
    public StringClauses newDefinition;

    public AlterTableAction() {
    }

    public AlterTableAction(ObjectReference table, StringClauses newDefinition) {
        this.table = table;
        this.newDefinition = newDefinition;
    }

}
