package liquibase.action.core;

import liquibase.action.AbstractAction;
import liquibase.item.core.ColumnReference;
import liquibase.util.StringClauses;

/**
 * Alters the given column to the {@link #newDefinition}. This action is not normally directly used but is instead generated by other Actions' ActionLogic.
 */
public class AlterColumnAction extends AbstractAction {

    public ColumnReference column;
    public StringClauses newDefinition;

    /**
     * Alternate keyword to use instead of "ALTER COLUMN" or whatever is standard for the database.
     */
    public String alterColumnKeyword;

    public AlterColumnAction() {
    }

    public AlterColumnAction(ColumnReference column, StringClauses newDefinition) {
        this.column = column;
        this.newDefinition = newDefinition;
    }

}
