package liquibase.action.core;

import liquibase.action.AbstractAction;
import liquibase.item.core.RelationReference;
import liquibase.util.StringClauses;

/**
 * Alters the given table to the {@link #newDefinition}. This action is not normally directly used but is instead generated by other Actions' ActionLogic.
 */
public class AlterTableAction extends AbstractAction {

    public RelationReference table;
    public StringClauses newDefinition;

    public AlterTableAction() {
    }

    public AlterTableAction(RelationReference table, StringClauses newDefinition) {
        this.table = table;
        this.newDefinition = newDefinition;
    }

}
